export const GET_POPULAR = "GET_POPULAR";
export const GET_TOP_RATED = "GET_TOP_RATED";
export const GET_UPCOMING = "GET_UPCOMING";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const GET_CREDIT_DETAILS = "GET_CREDIT_DETAILS";
export const GET_IMAGES = "GET_IMAGES";
